# Generated by Django 4.1 on 2022-09-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_user_averagescore_alter_user_quizzescompleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bestCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usersBestCatgeory', to='quizzes.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='worstCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usersWorstCatgeory', to='quizzes.category'),
        ),
    ]
