# Generated by Django 4.1 on 2022-09-03 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_user_bestcategory_alter_user_worstcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
