# Generated by Django 4.1 on 2022-09-03 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_question_answers_alter_quiz_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
