# Generated by Django 4.1 on 2022-09-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
