# Generated by Django 4.1 on 2022-09-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_alter_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
