# Generated by Django 4.1 on 2022-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_questionnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='averageScore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bestCategory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quizzesCreated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='worstCategory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quizzesCompleted',
        ),
        migrations.AddField(
            model_name='user',
            name='quizzesCompleted',
            field=models.ManyToManyField(blank=True, to='quizzes.quiz'),
        ),
    ]
