# Generated by Django 4.1 on 2022-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_category_correctanswers_category_incorrectanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='correctAnswers',
        ),
        migrations.RemoveField(
            model_name='category',
            name='incorrectAnswers',
        ),
        migrations.AddField(
            model_name='user',
            name='correctAnswers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='incorrectAnswers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
