# Generated by Django 4.1 on 2022-09-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_remove_category_correctanswers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='likes',
        ),
    ]
