# Generated by Django 4.1 on 2022-09-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_remove_quiz_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correctAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='incorrectAnswers',
            field=models.IntegerField(default=0),
        ),
    ]
