# Generated by Django 4.1 on 2022-09-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_alter_user_correctanswers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='averageScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bestCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best', to='quizzes.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='quizzesCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quizzesCreated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='worstCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worst', to='quizzes.category'),
        ),
    ]
