# Generated by Django 4.1 on 2022-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_alter_user_averagescore_alter_user_bestcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='averageScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
